info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T04:05:42.424Z"}
info: Connected to the database. {"timestamp":"2022-05-28T04:05:42.923Z"}
info: Server started at http://localhost:3000/api/v1/ {"timestamp":"2022-05-28T04:11:47.425Z"}
info: Connected to the database. {"timestamp":"2022-05-28T04:11:47.618Z"}
error: 
    status - 500 
    message - Error: Password not match
    at _callee3$ (C:\Users\user\Desktop\FundooNotes\FundooNotes\src\services\/user.service.js:30:13)
    at tryCatch (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:86:17)
    at Generator._invoke (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:66:24)
    at Generator.next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:117:21)
    at asyncGeneratorStep (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (C:\Users\user\Desktop\FundooNotes\FundooNotes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:25:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-05-28T04:11:53.306Z"}
